"""Referee check R2: exact intersection numbers of the known short-arc rational curves with E and K.

For a map Gamma: P^1 -> X_M given by coprime binary forms of degree d (Gaussian coefficients,
z_j = x_j + i y_j), H.Gamma = d and E.Gamma~ = deg of the homogeneous gcd of all difference forms
z_j - z_1 (the pull-back of the ideal of the diagonal line Y, generated by x_j-x_1, y_j-y_1; for
forms with Gaussian coefficients, gcd over Q(i) of the z_j - z_1 and their conjugates).
Then on Bl_Y X_M:  K.Gamma~ = -2d + (M-2) E.Gamma~.
Vojta V(M,eps) forces every rational curve with K.Gamma~ > eps*d into the exceptional set Z.
Families: Cilleruelo-Granville prod_{k=1}^d (a+k+i sigma_k) with sum(sigma) fixed (d=4,5,6),
and the eight-point translated Pell quartic (author's construction, re-used only to define it).
Exact arithmetic over Q(i) with Fractions.
"""
import sys
from fractions import Fraction as Fr
from itertools import product, combinations
sys.path.insert(0, __file__.rsplit('/', 1)[0] + '/rerun')

# Gaussian rationals as (re, im) Fractions; polynomials = list of coeffs, low degree first
def gadd(a, b): return (a[0] + b[0], a[1] + b[1])
def gsub(a, b): return (a[0] - b[0], a[1] - b[1])
def gmul(a, b): return (a[0] * b[0] - a[1] * b[1], a[0] * b[1] + a[1] * b[0])
def gconj(a): return (a[0], -a[1])
def ginv(a):
    n = a[0] * a[0] + a[1] * a[1]
    return (a[0] / n, -a[1] / n)
Z = (Fr(0), Fr(0)); ONE = (Fr(1), Fr(0))
def trim(P):
    while P and P[-1] == Z: P = P[:-1]
    return P
def pmul(P, Q):
    if not P or not Q: return []
    out = [Z] * (len(P) + len(Q) - 1)
    for i, a in enumerate(P):
        for j, b in enumerate(Q):
            out[i + j] = gadd(out[i + j], gmul(a, b))
    return trim(out)
def psub(P, Q):
    n = max(len(P), len(Q))
    P = P + [Z] * (n - len(P)); Q = Q + [Z] * (n - len(Q))
    return trim([gsub(a, b) for a, b in zip(P, Q)])
def pmod(P, Q):
    P = trim(list(P)); Q = trim(Q)
    inv = ginv(Q[-1])
    while len(P) >= len(Q):
        c = gmul(P[-1], inv); sh = len(P) - len(Q)
        P = psub(P, [Z] * sh + [gmul(c, q) for q in Q])
    return P
def pgcd(P, Q):
    P, Q = trim(P), trim(Q)
    while Q:
        P, Q = Q, pmod(P, Q)
    return P
def pconj(P): return [gconj(c) for c in P]

def homog_gcd_degree(forms, d):
    """forms: dehomogenized polys (in X, Y=1) of homogeneous degree d. Return deg of homogeneous gcd."""
    nz = [f for f in forms if f]
    if not nz: return None
    g = []
    for f in nz:
        g = pgcd(g, f) if g else f
    finite = len(g) - 1
    at_inf = min(d - (len(f) - 1) for f in nz)
    return finite + at_inf, finite, at_inf

def curve_numbers(points, d):
    # points: list of dehomogenized Gaussian polys z_j(X), each of degree <= d (homog degree d)
    coords_gcd = homog_gcd_degree(points + [pconj(p) for p in points], d)
    diffs = [psub(p, points[0]) for p in points[1:]]
    diffs = diffs + [pconj(f) for f in diffs]
    return coords_gcd, homog_gcd_degree(diffs, d)

def cg_family(d, s):
    sig = [x for x in product((1, -1), repeat=d) if sum(x) == s]
    pts = []
    for x in sig:
        P = [ONE]
        for k in range(1, d + 1):
            P = pmul(P, [(Fr(k), Fr(x[k - 1])), ONE])   # (a + k + i sigma_k)
        pts.append(P)
    return sig, pts

def report(name, pts, d, M):
    best = None; worst = None; cnt = 0
    for S in combinations(range(len(pts)), M):
        cg, (e, fin, inf) = curve_numbers([pts[i] for i in S], d)
        assert cg[0] == 0, "coordinate forms not coprime"
        K = -2 * d + (M - 2) * e
        best = K if best is None else max(best, K); worst = K if worst is None else min(worst, K)
        cnt += 1
        if cnt == 1:
            print(f"   e.g. first {M}-subtuple: E.G={e} (finite {fin}, at a=inf {inf}), K.G={K}")
    print(f"   {name}: {cnt} {M}-subtuples of {len(pts)} points, degree d={d}: K.Gamma~ ranges [{worst},{best}],"
          f"  eps threshold K.G/d: [{worst/d:.3f},{best/d:.3f}]")

if __name__ == '__main__':
    print("R2: intersection numbers on Bl_Y X_M; K.G = -2d + (M-2) E.G")
    for d, s, M in [(4, 0, 6), (5, 1, 7), (5, 1, 8), (6, 0, 7), (6, 0, 8), (6, 0, 9)]:
        sig, pts = cg_family(d, s)
        print(f" CG family d={d}, sum sigma={s}: {len(pts)} points")
        report(f"CG d={d}", pts, d, M)
    # Pell eight-point quartic (author's definition from primitive_eight_point_translated_pell_family.md)
    from check_vojta_geometry import H_lin, F
    from gauss import conj
    words = []
    for word in product((0, 1), repeat=4):
        p = sum(word)
        if p % 2 == 0: continue
        Pd = {(0, 0): F if p == 1 else conj(F)}
        from check_vojta_geometry import pmul as hpmul, pconj as hpconj
        for f, w in zip((H_lin(-2), H_lin(0), H_lin(2), H_lin(4)), word):
            Pd = hpmul(Pd, f if w else hpconj(f))
        # dehomogenize: X^a Y^b -> X^a  (Y=1); homogeneous degree 4
        P = [Z] * 5
        for (a, b), c in Pd.items():
            assert a + b == 4
            P[a] = gadd(P[a], (Fr(c[0]), Fr(c[1])))
        words.append(trim(P))
    print(" Pell eight-point quartic: 8 points")
    report("Pell", words, 4, 7)
    report("Pell", words, 4, 8)
    # which finite points: gcd of all differences for all 8
    diffs = [psub(p, words[0]) for p in words[1:]]
    g = []
    for f in diffs + [pconj(f) for f in diffs]:
        g = pgcd(g, f) if g else f
    lc = ginv(g[-1]); g = [gmul(c, lc) for c in g]
    print(f"   monic gcd of all Pell differences (in X, Y=1): {[(str(c[0]), str(c[1])) for c in g]}")
