[package]
name = "Jarnik"
version = "0.1.0"
authors = ["Craig Chen <craig.chen@duke.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
