[package]
name = "jarnik"
version = "0.1.0"
authors = ["Craig Chen <craig.chen@duke.edu>"]
edition = "2018"

[dependencies]
csv = "*"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench_main"
harness = false
