import GaussianChain.PrimeRevealCube

namespace GaussianChain.PrimeReveal

/-- The completion count at one corner of the two-prime face generated by
coordinates `i` and `j`. -/
def faceCount {n : ℕ} (A : Finset (SignVector n))
    (a : PartialSignVector n) (i j : Fin n) (bi bj : Bool) : ℕ :=
  completionCount A (reveal (reveal a i bi) j bj)

/-- Swapping the order of the two reveals does not change a face count. -/
theorem faceCount_swap_reveal_order {n : ℕ} (A : Finset (SignVector n))
    (a : PartialSignVector n) (i j : Fin n) (bi bj : Bool) (h : i ≠ j) :
    faceCount A a i j bi bj =
      completionCount A (reveal (reveal a j bj) i bi) := by
  exact completionCount_reveal_commute A a i j bi bj h

/-- Swapping the two coordinate names transposes the reveal face. -/
theorem faceCount_swap_coordinates {n : ℕ} (A : Finset (SignVector n))
    (a : PartialSignVector n) (i j : Fin n) (bi bj : Bool) (h : i ≠ j) :
    faceCount A a i j bi bj = faceCount A a j i bj bi := by
  exact completionCount_reveal_commute A a i j bi bj h

/-- The signed interaction curvature of a two-prime reveal face.
It is the cross-product `C₊₊ C₋₋ - C₊₋ C₋₊`. -/
def faceCurvature {n : ℕ} (A : Finset (SignVector n))
    (a : PartialSignVector n) (i j : Fin n) : ℤ :=
  (faceCount A a i j true true : ℤ) *
      (faceCount A a i j false false : ℤ) -
    (faceCount A a i j true false : ℤ) *
      (faceCount A a i j false true : ℤ)

/-- The interaction curvature is symmetric in the two revealed primes. -/
theorem faceCurvature_swap {n : ℕ} (A : Finset (SignVector n))
    (a : PartialSignVector n) (i j : Fin n) (h : i ≠ j) :
    faceCurvature A a i j = faceCurvature A a j i := by
  simp only [faceCurvature]
  rw [faceCount_swap_coordinates A a i j true true h,
    faceCount_swap_coordinates A a i j false false h,
    faceCount_swap_coordinates A a i j true false h,
    faceCount_swap_coordinates A a i j false true h]
  ring

/-- Vanishing curvature is exactly the multiplicative cross-product identity
for the four grandchild completion counts. -/
theorem faceCurvature_eq_zero_iff {n : ℕ} (A : Finset (SignVector n))
    (a : PartialSignVector n) (i j : Fin n) :
    faceCurvature A a i j = 0 ↔
      faceCount A a i j true true * faceCount A a i j false false =
        faceCount A a i j true false * faceCount A a i j false true := by
  simp only [faceCurvature]
  norm_num

/-- If both coordinates are unrevealed, the parent completion count is the
sum of all four two-prime face counts. -/
theorem completionCount_eq_sum_face {n : ℕ} (A : Finset (SignVector n))
    (a : PartialSignVector n) (i j : Fin n) (hij : i ≠ j)
    (hi : a i = none) (hj : a j = none) :
    completionCount A a =
      faceCount A a i j true true + faceCount A a i j true false +
      faceCount A a i j false true + faceCount A a i j false false := by
  rw [completionCount_eq_children A a i hi]
  have hjTrue : reveal a i true j = none := by
    simp [reveal, hij.symm, hj]
  have hjFalse : reveal a i false j = none := by
    simp [reveal, hij.symm, hj]
  rw [completionCount_eq_children A (reveal a i true) j hjTrue,
    completionCount_eq_children A (reveal a i false) j hjFalse]
  rfl

end GaussianChain.PrimeReveal
