import Mathlib

namespace GaussianChain.PrimeReveal

/-- A squarefree Gaussian divisor orientation pattern. `true` and `false`
represent the two conjugate choices above a split rational prime. -/
abbrev SignVector (n : ℕ) := Fin n → Bool

/-- The signed angular contribution of one revealed prime. -/
def signedContribution (b : Bool) (x : ℝ) : ℝ :=
  if b then x else -x

/-- The total lifted angle attached to an orientation pattern. -/
def angleSum {n : ℕ} (θ : Fin n → ℝ) (ε : SignVector n) : ℝ :=
  ∑ i, signedContribution (ε i) (θ i)

/-- Membership in a lifted angular window centered at `c` with radius `δ`. -/
def InWindow {n : ℕ} (θ : Fin n → ℝ) (c δ : ℝ) (ε : SignVector n) : Prop :=
  |angleSum θ ε - c| ≤ δ

/-- The finite successful fiber cut out by an angular window. -/
def successfulFiber {n : ℕ} (θ : Fin n → ℝ) (c δ : ℝ) : Finset (SignVector n) :=
  Finset.univ.filter (InWindow θ c δ)

@[simp]
theorem mem_successfulFiber {n : ℕ} (θ : Fin n → ℝ) (c δ : ℝ) (ε : SignVector n) :
    ε ∈ successfulFiber θ c δ ↔ InWindow θ c δ ε := by
  simp [successfulFiber]

/-- The two children obtained when the orientation at `i` is revealed. -/
def trueChild {n : ℕ} (A : Finset (SignVector n)) (i : Fin n) : Finset (SignVector n) :=
  A.filter fun ε ↦ ε i = true

def falseChild {n : ℕ} (A : Finset (SignVector n)) (i : Fin n) : Finset (SignVector n) :=
  A.filter fun ε ↦ ε i = false

@[simp]
theorem mem_trueChild {n : ℕ} (A : Finset (SignVector n)) (i : Fin n) (ε : SignVector n) :
    ε ∈ trueChild A i ↔ ε ∈ A ∧ ε i = true := by
  simp [trueChild]

@[simp]
theorem mem_falseChild {n : ℕ} (A : Finset (SignVector n)) (i : Fin n) (ε : SignVector n) :
    ε ∈ falseChild A i ↔ ε ∈ A ∧ ε i = false := by
  simp [falseChild]

theorem child_disjoint {n : ℕ} (A : Finset (SignVector n)) (i : Fin n) :
    Disjoint (trueChild A i) (falseChild A i) := by
  rw [Finset.disjoint_left]
  intro ε htrue hfalse
  have ht : ε i = true := ((mem_trueChild A i ε).mp htrue).2
  have hf : ε i = false := ((mem_falseChild A i ε).mp hfalse).2
  simp [ht] at hf

theorem child_union {n : ℕ} (A : Finset (SignVector n)) (i : Fin n) :
    trueChild A i ∪ falseChild A i = A := by
  ext ε
  cases h : ε i <;> simp [trueChild, falseChild, h]

/-- Revealing one prime partitions the successful completions exactly. -/
theorem card_eq_child_cards {n : ℕ} (A : Finset (SignVector n)) (i : Fin n) :
    A.card = (trueChild A i).card + (falseChild A i).card := by
  rw [← Finset.card_union_of_disjoint (child_disjoint A i), child_union]

/-- Two successful sign patterns in the same radius-`δ` lifted window differ
in total angle by at most `2δ`. This is the deterministic repair relation
behind every genuine branch of the reveal tree. -/
theorem pair_repair_bound {n : ℕ} (θ : Fin n → ℝ) (c δ : ℝ)
    (x y : SignVector n) (hx : InWindow θ c δ x) (hy : InWindow θ c δ y) :
    |angleSum θ x - angleSum θ y| ≤ 2 * δ := by
  calc
    |angleSum θ x - angleSum θ y| =
        |(angleSum θ x - c) - (angleSum θ y - c)| := by ring
    _ ≤ |angleSum θ x - c| + |angleSum θ y - c| := abs_sub _ _
    _ ≤ δ + δ := add_le_add hx hy
    _ = 2 * δ := by ring

/-- Agreement on all coordinates before `k`, used to express the triangular
shape of repair relations generated by a fixed reveal order. -/
def AgreeBefore {n : ℕ} (k : ℕ) (x y : SignVector n) : Prop :=
  ∀ i : Fin n, i.1 < k → x i = y i

/-- A genuine branch at coordinate `k`: the two completions agree on every
previously revealed coordinate and choose opposite signs at `k`. -/
def BranchPair {n : ℕ} (k : Fin n) (x y : SignVector n) : Prop :=
  AgreeBefore k.1 x y ∧ x k ≠ y k

/-- Abstract interface for the missing arithmetic theorem. The predicate
`Admissible n θ δ` is where one records that the angles come from distinct
Gaussian prime quotients and that `δ` is the critical conductor scale.
No claim is made for arbitrary real angle lists. -/
def UniformFiberBoundFor
    (Admissible : ∀ n : ℕ, (Fin n → ℝ) → ℝ → Prop) : Prop :=
  ∃ K : ℕ, ∀ (n : ℕ) (θ : Fin n → ℝ) (c δ : ℝ),
    Admissible n θ δ → (successfulFiber θ c δ).card ≤ K

end GaussianChain.PrimeReveal
