# Alternating measures on the shell S={k in Z^M: sum k = s, ||k||_1 = t}.
# order = C(M,2) + e, e = max degree such that some nonzero c'' on sorted reps (distinct entries)
# is orthogonal to all symmetric polys of degree < e (generated by power sums p_2..p_M; p_1 = s fixed).
import itertools, sys
from math import comb
P = 2**61 - 1
def reps(M, s, t):
    out = []
    # strictly decreasing tuples k_1 > ... > k_M, sum s, l1 = t
    def rec(prefix, maxv, rem_sum, rem_l1, left):
        if left == 0:
            if rem_sum == 0 and rem_l1 == 0: out.append(tuple(prefix))
            return
        # minimal l1 for 'left' distinct values below maxv: crude prune
        for v in range(min(maxv, rem_l1), -rem_l1 - 1, -1):
            if abs(v) > rem_l1: continue
            rec(prefix + [v], v - 1, rem_sum - v, rem_l1 - abs(v), left - 1)
    rec([], t, s, t, M)
    return out
def wmonomials(M, e):  # monomials in p_2..p_M of weighted degree <= e
    parts = list(range(2, M + 1))
    out = []
    def rec(i, rem, cur):
        if i == len(parts):
            out.append(tuple(cur)); return
        w = parts[i]
        for a in range(rem // w + 1):
            rec(i + 1, rem - a * w, cur + [a])
    rec(0, e, [])
    return out
def rank_mod(rows, p):
    rows = [r[:] for r in rows]; rank = 0
    ncol = len(rows[0]) if rows else 0
    for col in range(ncol):
        piv = next((i for i in range(rank, len(rows)) if rows[i][col] % p), None)
        if piv is None: continue
        rows[rank], rows[piv] = rows[piv], rows[rank]
        inv = pow(rows[rank][col], p - 2, p)
        rows[rank] = [x * inv % p for x in rows[rank]]
        for i in range(len(rows)):
            if i != rank and rows[i][col] % p:
                f = rows[i][col]; rows[i] = [(a - f * b) % p for a, b in zip(rows[i], rows[rank])]
        rank += 1
        if rank == len(rows): break
    return rank
def e_max(M, s, t):
    R = reps(M, s, t)
    n = len(R)
    if n == 0: return None, 0
    ps = [[sum(x ** j for x in r) % P for j in range(2, M + 1)] for r in R]
    e = 0
    while True:
        mons = wmonomials(M, e)
        rows = []
        for a in mons:
            row = []
            for pv in ps:
                v = 1
                for base, ex in zip(pv, a):
                    if ex: v = v * pow(base, ex, P) % P
                row.append(v)
            rows.append(row)
        if rank_mod(rows, P) == n: return e, n
        e += 1
if __name__ == '__main__':
    for M in range(int(sys.argv[1]), int(sys.argv[2]) + 1):
        sv = M * (M - 1) // 2
        # minimal l1 for M distinct integers with sum s
        best = (0,)
        for s in range(0, 3):
            base = sum(abs(x) for x in range(-(M // 2), M - M // 2))  # rough minimal
            for t in range(1, base + int(sys.argv[3]) + 1):
                if (t - s) % 2: continue
                e, n = e_max(M, s, t)
                if e is None: continue
                order = sv + e
                ratio = order / t
                if ratio > best[0]: best = (ratio, s, t, n, e, order)
                if ratio >= 1.6: print(f"M={M} s={s} t={t} reps={n} e={e} order={order} ratio={ratio:.4f}", flush=True)
        print("BEST", M, best, flush=True)
