# Symmetric (S_M-invariant) measures on the shell {sum k = s, ||k||_1 = t}: order = max m with nonzero
# invariant c orthogonal to all symmetric polys of degree < m (generated by p_2..p_M, p_1 = s fixed).
import sys
P = 2**61 - 1
def orbits(M, s, t):
    out = []
    def rec(prefix, maxv, rem_sum, rem_l1, left):
        if left == 0:
            if rem_sum == 0 and rem_l1 == 0: out.append(tuple(prefix))
            return
        for v in range(min(maxv, rem_l1), -rem_l1 - 1, -1):
            if abs(v) > rem_l1: continue
            rec(prefix + [v], v, rem_sum - v, rem_l1 - abs(v), left - 1)
    rec([], t, s, t, M)
    return out
def wmonomials(M, e):
    parts = list(range(2, M + 1)); out = []
    def rec(i, rem, cur):
        if i == len(parts): out.append(tuple(cur)); return
        w = parts[i]
        for a in range(rem // w + 1): rec(i + 1, rem - a * w, cur + [a])
    rec(0, e, []); return out
def rank_mod(rows, p):
    rows = [r[:] for r in rows]; rank = 0; ncol = len(rows[0]) if rows else 0
    for col in range(ncol):
        piv = next((i for i in range(rank, len(rows)) if rows[i][col] % p), None)
        if piv is None: continue
        rows[rank], rows[piv] = rows[piv], rows[rank]
        inv = pow(rows[rank][col], p - 2, p); rows[rank] = [x * inv % p for x in rows[rank]]
        for i in range(len(rows)):
            if i != rank and rows[i][col] % p:
                f = rows[i][col]; rows[i] = [(a - f * b) % p for a, b in zip(rows[i], rows[rank])]
        rank += 1
        if rank == len(rows): break
    return rank
def order(M, s, t):
    O = orbits(M, s, t); n = len(O)
    if n == 0: return None, 0
    ps = [[sum(x ** j for x in r) % P for j in range(2, M + 1)] for r in O]
    m = 0
    while True:
        rows = []
        for a in wmonomials(M, m):
            row = []
            for pv in ps:
                v = 1
                for b, ex in zip(pv, a):
                    if ex: v = v * pow(b, ex, P) % P
                row.append(v)
            rows.append(row)
        if rank_mod(rows, P) == n: return m, n
        m += 1
for M in range(int(sys.argv[1]), int(sys.argv[2]) + 1):
    best = (0,)
    for t in range(1, int(sys.argv[3]) + 1):
        for s in range(0, min(t, 4) + 1):
            if (t - s) % 2: continue
            m, n = order(M, s, t)
            if m is None: continue
            if m / t > best[0]: best = (m / t, s, t, n, m)
    print("SYM BEST", M, best, flush=True)
