"""Random search over S_M-symmetric cut polytopes generated by a few integer vectors:
U_b = max_t top_b(v^t) (tight, exact), widths w_b = max_t top_b - min_t bottom_b (exact, attained by
generator points), adversary = best half-separating symmetric cut measure (exact),
peel = rigorous upper bound for reg(S(nU)) (sorted coordinate peeling).  Reports max peel/(2 n adv)."""
import sys, random
from fractions import Fraction as Fr
from peeldp import bound
from clib import sym_adversary
random.seed(int(sys.argv[4]))
M = int(sys.argv[1]); trials = int(sys.argv[2]); R = int(sys.argv[3]); n = int(sys.argv[5]) if len(sys.argv) > 5 else 2

def tops(v):
    vs = sorted(v, reverse=True); out = []; a = 0
    for b in range(1, M):
        a += vs[b-1]; out.append(a)
    return out

best = []
for t in range(trials):
    r = random.randint(1, 3)
    s = random.randint(-M + 1, M - 1)
    gens = []
    for _ in range(r):
        v = [random.randint(-R, R) for _ in range(M - 1)]
        v.append(s - sum(v))
        gens.append(v)
    U = [max(tops(v)[b] for v in gens) for b in range(M - 1)]
    # widths for |B| = b : max top_b - min bottom_b ; bottom_b = s - top_{M-b}
    w = {}
    for b in range(1, M // 2 + 1):
        mx = max(tops(v)[b-1] for v in gens)
        mn = min(s - tops(v)[M-b-1] for v in gens)
        # also cut of size M-b has the same width as size b (complement)
        w[b] = mx - mn
    if all(x == 0 for x in w.values()): continue
    adv, mu = sym_adversary(w, M)
    Un = tuple(n * u for u in U)
    pb = bound(M, Un, n * s)
    ratio = Fr(pb, 1) / (2 * n * adv)
    best.append((ratio, pb, adv, U, s, w, gens))
best.sort(key=lambda x: -x[0])
print(f"M={M} trials={len(best)} n={n}: max peel/(2 n adv) = {float(best[0][0]):.4f}")
for x in best[:5]:
    print(f"   ratio={float(x[0]):.4f} peel={x[1]} adv={x[2]} U={x[3]} s={x[4]} w={x[5]} gens={x[6]}")
